export const frasesCelebres = [
  { texto: "La vida es lo que sucede mientras estás ocupado haciendo otros planes.", autor: "John Lennon" },
  { texto: "El único modo de hacer un gran trabajo es amar lo que haces.", autor: "Steve Jobs" },
  { texto: "Si lo puedes soñar, lo puedes hacer.", autor: "Walt Disney" },
  { texto: "La innovación distingue a un líder de un seguidor.", autor: "Steve Jobs" },
  { texto: "La vida es 10% lo que te sucede y 90% cómo reaccionas ante ello.", autor: "Charles R. Swindoll" },
  { texto: "El futuro pertenece a quienes creen en la belleza de sus sueños.", autor: "Eleanor Roosevelt" },
  { texto: "Es durante nuestros momentos más oscuros que debemos enfocarnos en ver la luz.", autor: "Aristoteles" },
  { texto: "La única manera de hacer que el tiempo sea tuyo es ganártelo.", autor: "Pablo Neruda" },
  { texto: "No importa cuán lentamente vayas, mientras no pares.", autor: "Confucio" },
  { texto: "El éxito no es final, el fracaso no es fatal: lo que cuenta es el coraje de continuar.", autor: "Winston Churchill" },
  { texto: "Eres más valiente de lo que crees, más fuerte de lo que parece, y más inteligente de lo que piensas.", autor: "A.A. Milne" },
  { texto: "El dinero nunca duerme, ni debería dormir tu ambición.", autor: "Robert Kiyosaki" },
  { texto: "No puedes cambiar el futuro, pero sí puedes cambiar tu reacción ante él.", autor: "Brian Tracy" },
  { texto: "La mejor forma de predecir el futuro es inventarlo.", autor: "Peter Drucker" },
  { texto: "No busques culpables, busca soluciones.", autor: "Henry Ford" },
  { texto: "La disciplina es elegir lo que quieres más, ahora mismo.", autor: "David Goggins" },
  { texto: "El éxito es la suma de pequeños esfuerzos realizados día tras día.", autor: "Robert Collier" },
  { texto: "No es la montaña la que conquistamos, sino a nosotros mismos.", autor: "Edmund Hillary" },
  { texto: "El único fracaso real es dejar de intentar.", autor: "John C. Maxwell" },
  { texto: "Tu actitud determina tu altitud.", autor: "Zig Ziglar" },
  { texto: "La grandeza no es por circunstancia, sino por determinación.", autor: "Desconocido" },
  { texto: "El éxito es caminar de fracaso a fracaso sin perder el entusiasmo.", autor: "Winston Churchill" },
  { texto: "No esperes oportunidades, créalas.", autor: "Chris Grosser" },
  { texto: "La única limitación es la que establecemos en nuestras mentes.", autor: "Napoleon Hill" },
  { texto: "Cada día es una segunda oportunidad para hacer las cosas bien.", autor: "Ralph Marston" },
  { texto: "Nadie puede hacerte sentir inferior sin tu consentimiento.", autor: "Eleanor Roosevelt" },
  { texto: "La paciencia es amarga, pero su fruto es dulce.", autor: "Jean-Jacques Rousseau" },
  { texto: "El coraje es tener miedo pero seguir adelante.", autor: "Susan David" },
  { texto: "Tus limitaciones son solo el comienzo de tus posibilidades.", autor: "Jack Canfield" },
  { texto: "La vida es un 10% de lo que te ocurre y un 90% de cómo lo enfrentas.", autor: "Charles Swindoll" },
  { texto: "El fracaso es solo retroalimentación en el camino hacia el éxito.", autor: "John C. Maxwell" },
  { texto: "Lo que la mente puede concebir y creer, puede lograr.", autor: "Napoleon Hill" },
  { texto: "No confundas tu valor con tu producción.", autor: "Brené Brown" },
  { texto: "Eres responsable de tu propia felicidad.", autor: "Steve Maraboli" },
  { texto: "La perfección es enemiga del bien.", autor: "Voltaire" },
  { texto: "No importa dónde estés, siempre hay algo más que puedas hacer.", autor: "Zig Ziglar" },
  { texto: "El tiempo es lo más valioso que tienes, úsalo sabiamente.", autor: "Steve Jobs" },
  { texto: "No busques atajos, busca el camino correcto.", autor: "Desconocido" },
  { texto: "La creatividad es la inteligencia divirtiéndose.", autor: "Albert Einstein" },
  { texto: "La vida es demasiado corta para vivir una vida pequeña.", autor: "Alan Watts" },
  { texto: "El conocimiento es poder, pero el uso del conocimiento es todavía más poderoso.", autor: "Desconocido" },
  { texto: "Nadie puede darte las riendas de tu vida, solo tú puedes hacerlo.", autor: "Oprah Winfrey" },
  { texto: "La mejor inversión es en ti mismo.", autor: "Warren Buffett" },
  { texto: "No es lo que sucede, es cómo reaccionas lo que importa.", autor: "Epicteto" },
  { texto: "La vida comienza donde termina tu miedo.", autor: "Osho" },
  { texto: "Tus sueños no tienen fecha de vencimiento.", autor: "Aimee Allen" },
  { texto: "El optimismo es la fe que conduce al éxito.", autor: "Helen Keller" },
  { texto: "Hazlo ahora, porque el futuro no está garantizado.", autor: "Desconocido" },
  { texto: "La verdadera riqueza no es dinero, es tiempo.", autor: "Desconocido" },
  { texto: "El sacrificio es la semilla del éxito.", autor: "Paulo Coelho" },
  { texto: "Tu éxito no es responsabilidad de nadie más que tuya.", autor: "Will Smith" },
  { texto: "La adversidad es la verdadera escuela de la genialidad.", autor: "Napoleon Bonaparte" },
  { texto: "No necesitas permiso para ser excelente.", autor: "Desconocido" },
  { texto: "La única barrera entre tú y tu sueño eres tú.", autor: "Michael Phelps" },
  { texto: "El poder está en tus manos, úsalo.", autor: "Desconocido" },
  { texto: "La vida es una aventura atrevida o nada.", autor: "Helen Keller" },
  { texto: "Hoy es el primer día del resto de tu vida.", autor: "Charles Dederline" },
  { texto: "Muévete con un propósito.", autor: "Desconocido" },
  { texto: "No esperes a estar listo, comienza hoy.", autor: "Marie Forleo" },
  { texto: "El éxito es la suma de las pequeñas cosas realizadas consistentemente.", autor: "Desconocido" },
  { texto: "Tu única competencia eres tú ayer.", autor: "Desconocido" },
  { texto: "La vida no se trata de encontrarse, se trata de crearse.", autor: "George Bernard Shaw" },
  { texto: "Cada momento es una oportunidad para cambiar tu vida.", autor: "Desconocido" },
  { texto: "La decisión es tu derecho más sagrado.", autor: "Esther Hicks" },
  { texto: "No puedes cambiar lo que no reconoces.", autor: "Jack Canfield" },
  { texto: "Tu pasado no define tu futuro.", autor: "Joel Osteen" },
  { texto: "La vida es un juego, juega a ganar.", autor: "Desconocido" },
  { texto: "Eres el arquitecto de tu propio destino.", autor: "Desconocido" },
  { texto: "El éxito es la mejor venganza.", autor: "Kangana Ranaut" },
  { texto: "No hay que tener miedo de dar un gran paso, no puedes cruzar un abismo en dos pequeños saltos.", autor: "Lloyd George" },
  { texto: "La pasión es la brújula que te guía hacia tu propósito.", autor: "Desconocido" },
  { texto: "No dejes para mañana lo que puedas hacer hoy.", autor: "Benjamín Franklin" },
  { texto: "La vida es ahora, no esperes el mañana.", autor: "Desconocido" },
  { texto: "El éxito no viene de lo que haces ocasionalmente, sino de lo que haces consistentemente.", autor: "Marie Forleo" },
  { texto: "Tu mentalidad determina tu realidad.", autor: "Wayne Dyer" },
  { texto: "La vida es el viaje, no el destino.", autor: "Ralph Waldo Emerson" },
  { texto: "No es sobre ser el mejor, es sobre ser mejor que ayer.", autor: "Desconocido" },
  { texto: "La fe es ver la luz con el corazón cuando la razón ve la oscuridad.", autor: "Thomas Aquino" },
  { texto: "Eres más fuerte de lo que jamás has imaginado.", autor: "Desconocido" },
  { texto: "La vida es una broma, sonríe.", autor: "Desconocido" },
  { texto: "No te compares, inspírate.", autor: "Desconocido" },
  { texto: "El éxito es un viaje, no un destino.", autor: "Arthur Ashe" },
  { texto: "Tu potencial es ilimitado, solo cree en ti.", autor: "Desconocido" },
  { texto: "La gratitud abre puertas que el dinero no puede abrir.", autor: "Desconocido" },
  { texto: "La vida es lo que haces de ella.", autor: "Desconocido" },
  { texto: "No importa lo que pase, nunca pierdas la esperanza.", autor: "Desconocido" },
  { texto: "El cambio comienza en ti.", autor: "Desconocido" },
  { texto: "Tu voz importa, úsala.", autor: "Desconocido" },
  { texto: "La vida es un regalo, vívela plenamente.", autor: "Desconocido" },
  { texto: "No busques la perfección, busca el progreso.", autor: "Desconocido" },
  { texto: "Eres capaz de más de lo que crees.", autor: "Desconocido" },
  { texto: "La vida comienza fuera de tu zona de confort.", autor: "Neale Donald Walsch" },
  { texto: "No dejes que los miedos te paralicen.", autor: "Desconocido" },
  { texto: "El éxito es para aquellos que se atreven a soñar.", autor: "Desconocido" },
  { texto: "Tu tiempo es precioso, inviértelo en lo que importa.", autor: "Desconocido" },
  { texto: "La vida es una oportunidad, abraza cada momento.", autor: "Desconocido" },
  { texto: "No eres un accidente, tienes un propósito.", autor: "Rick Warren" },
  { texto: "El éxito es perseguir lo que amas.", autor: "Confucio" },
  { texto: "La vida es demasiado corta para desperdicio de energía.", autor: "Desconocido" },
  { texto: "Tu historia no ha terminado, escribe el siguiente capítulo.", autor: "Desconocido" },
  { texto: "La grandeza no es algo que sucede, es algo que haces.", autor: "Desconocido" },
  { texto: "No busques la salida, busca la entrada a tus sueños.", autor: "Desconocido" },
  { texto: "La vida es una serie de pruebas, supéralas.", autor: "Desconocido" },
  { texto: "El poder de la persistencia es imparable.", autor: "Desconocido" },
  { texto: "No importa cuánto caigas, lo importante es cuántas veces te levantes.", autor: "Desconocido" },
  { texto: "La vida es lo que tú haces que sea.", autor: "Desconocido" },
  { texto: "Tu actitud es tu poder más grande.", autor: "Desconocido" },
  { texto: "No hay éxito sin sacrificio.", autor: "Desconocido" },
  { texto: "La vida es una aventura, vívela.", autor: "Desconocido" },
  { texto: "Eres el dueño de tu destino.", autor: "Desconocido" },
  { texto: "El éxito es para los valientes.", autor: "Desconocido" },
  { texto: "Tu vida es tu mejor regalo.", autor: "Desconocido" },
  { texto: "No esperes, actúa ahora.", autor: "Desconocido" },
  { texto: "La vida es una bola de nieve, hazla rodar.", autor: "Desconocido" },
  { texto: "Tu futuro está en tus manos.", autor: "Desconocido" },
  { texto: "El éxito es una decisión, no una suerte.", autor: "Desconocido" },
  { texto: "La vida te ofrece opciones, elige sabiamente.", autor: "Desconocido" },
  { texto: "No eres lo que otros dicen que eres.", autor: "Desconocido" },
  { texto: "La grandeza está en tu interior.", autor: "Desconocido" },
  { texto: "La vida es una canción, cántala con tu corazón.", autor: "Desconocido" },
  { texto: "Tu éxito depende de tu disposición a trabajar duro.", autor: "Desconocido" },
  { texto: "No subestimes tu poder.", autor: "Desconocido" },
  { texto: "La vida es un juego de estrategia, juega bien.", autor: "Desconocido" },
  { texto: "Tu valor no se mide por lo que tienes.", autor: "Desconocido" },
  { texto: "El éxito es la acumulación de esfuerzos diarios.", autor: "Desconocido" },
  { texto: "La vida es una aventura sin fin.", autor: "Desconocido" },
  { texto: "Eres el capitán de tu barco.", autor: "Desconocido" },
  { texto: "No temas al fracaso, es el camino al éxito.", autor: "Desconocido" },
  { texto: "La vida está llena de sorpresas, disfrútalas.", autor: "Desconocido" },
  { texto: "Tu potencial es enorme, úsalo.", autor: "Desconocido" },
  { texto: "El éxito es para aquellos que nunca se rinden.", autor: "Desconocido" },
  { texto: "La vida es una segunda oportunidad cada mañana.", autor: "Desconocido" },
  { texto: "No busques la felicidad, crea la felicidad.", autor: "Desconocido" },
  { texto: "Tu vida es tu obra maestra.", autor: "Desconocido" },
  { texto: "La vida es lo que planeas que sea.", autor: "Desconocido" },
  { texto: "El éxito es la satisfacción de hacer lo que amas.", autor: "Desconocido" },
  { texto: "No importa dónde empieces, importa dónde acabas.", autor: "Desconocido" },
  { texto: "La vida es una prueba, aprende de ella.", autor: "Desconocido" },
  { texto: "Tu determinación te llevará al éxito.", autor: "Desconocido" },
  { texto: "No dejes que nadie robe tus sueños.", autor: "Desconocido" },
  { texto: "La vida es hermosa, aprecia cada momento.", autor: "Desconocido" },
  { texto: "Eres más talentoso de lo que crees.", autor: "Desconocido" },
  { texto: "El éxito comienza en tu mente.", autor: "Desconocido" },
  { texto: "La vida es un regalo, vívela al máximo.", autor: "Desconocido" },
  { texto: "No eres lo que pasó, eres lo que haces al respecto.", autor: "Desconocido" },
  { texto: "La grandeza nunca se entrega, se conquista.", autor: "Desconocido" },
  { texto: "Tu vida es tu lienzo, pinta tu masterpiece.", autor: "Desconocido" },
  { texto: "El éxito es la culminación de pequeñas victorias.", autor: "Desconocido" },
  { texto: "La vida es una oportunidad de crecer.", autor: "Desconocido" },
  { texto: "No te conformes con menos de lo que mereces.", autor: "Desconocido" },
  { texto: "La vida es corta, haz que cuente.", autor: "Desconocido" },
  { texto: "Tu éxito es tu mejor respuesta.", autor: "Desconocido" },
  { texto: "No busques culpas, busca soluciones.", autor: "Desconocido" },
  { texto: "La vida es lo que tú decides que sea.", autor: "Desconocido" },
  { texto: "El éxito es para los que osan soñar en grande.", autor: "Desconocido" },
  { texto: "La vida te da lo que mereces, así que sé digno.", autor: "Desconocido" },
  { texto: "Tu potencial es tu regalo más grande.", autor: "Desconocido" },
  { texto: "No hay límites para quien se atreve a soñar.", autor: "Desconocido" },
  { texto: "La vida es un viaje hermoso, disfruta el camino.", autor: "Desconocido" },
  { texto: "El éxito es la paz mental de saber que hiciste tu mejor esfuerzo.", autor: "John Wooden" },
  { texto: "La vida es tu responsabilidad, vívela con pasión.", autor: "Desconocido" },
  { texto: "No esperes la perfección, busca la excelencia.", autor: "Desconocido" },
  { texto: "Tu voz es poderosa, úsala para cambiar el mundo.", autor: "Desconocido" },
  { texto: "La vida es una bendición, agradécela.", autor: "Desconocido" },
  { texto: "El éxito es perseguir tu pasión con determinación.", autor: "Desconocido" },
  { texto: "La vida no es esperar a que pase, es hacerlo pasar.", autor: "Desconocido" },
  { texto: "Eres el héroe de tu propia historia.", autor: "Desconocido" },
  { texto: "No busques la felicidad en otros, búscala en ti.", autor: "Desconocido" },
  { texto: "La vida es una serie de elecciones, elige bien.", autor: "Desconocido" },
  { texto: "Tu éxito es tu mejor motivación.", autor: "Desconocido" },
  { texto: "La vida es lo que haces en tus momentos libres.", autor: "Charles Schwab" },
  { texto: "No te desanimes, el éxito es una montaña, no una colina.", autor: "Desconocido" },
  { texto: "La vida es una batalla, lucha por lo que amas.", autor: "Desconocido" },
  { texto: "El éxito es la suma de pequeños logros.", autor: "Desconocido" },
  { texto: "Tu vida tiene un propósito, encuéntralo.", autor: "Desconocido" },
  { texto: "La vida es un espejo, refleja lo que eres.", autor: "Desconocido" },
  { texto: "No busques la salida, busca la entrada.", autor: "Desconocido" },
  { texto: "La vida es lo que tú decides que sea cada día.", autor: "Desconocido" },
  { texto: "El éxito es la recompensa de la consistencia.", autor: "Desconocido" },
  { texto: "Tu vida es valiosa, vívela con dignidad.", autor: "Desconocido" },
  { texto: "No hay nada imposible si crees en ti.", autor: "Desconocido" },
  { texto: "La vida es una aventura, sé el protagonista.", autor: "Desconocido" },
  { texto: "Tu éxito es tu mejor venganza.", autor: "Desconocido" },
  { texto: "La vida no te prepara, tú te preparas para la vida.", autor: "Desconocido" },
  { texto: "El éxito es la libertad financiera y emocional.", autor: "Robert Kiyosaki" },
  { texto: "La vida es un regalo, ábrelo cada día.", autor: "Desconocido" },
  { texto: "No eres una víctima de las circunstancias, eres el creador de tu realidad.", autor: "Wayne Dyer" },
  { texto: "La vida es corta, ama profundamente.", autor: "Desconocido" },
  { texto: "Tu éxito es tu esperanza para el mundo.", autor: "Desconocido" },
  { texto: "La vida es lo que sucede cuando estás ocupado haciendo otros planes.", autor: "John Lennon" },
  { texto: "No busques la seguridad, busca la aventura.", autor: "Desconocido" },
  { texto: "La vida es una prueba de carácter, pásala.", autor: "Desconocido" },
  { texto: "El éxito es la brújula que te guía hacia tu destino.", autor: "Desconocido" },
  { texto: "Tu vida es tu mejor inversión.", autor: "Desconocido" },
  { texto: "La vida es una canción hermosa, cántala.", autor: "Desconocido" },
  { texto: "No tengas miedo de ser grande.", autor: "Marianne Williamson" },
  { texto: "La vida es para los valientes, sé uno de ellos.", autor: "Desconocido" },
  { texto: "Tu éxito es tu mejor inspiración.", autor: "Desconocido" },
  { texto: "La vida no es un destino, es un viaje.", autor: "Desconocido" },
  { texto: "El éxito es la paz de saber que hiciste bien.", autor: "Desconocido" },
  { texto: "Tu vida es tu poder, úsalo.", autor: "Desconocido" },
  { texto: "La vida es lo que haces de ella con lo que tienes.", autor: "Desconocido" },
  { texto: "No esperes a ser perfecto, sé consistente.", autor: "Desconocido" },
  { texto: "La vida es una oportunidad de ser feliz.", autor: "Desconocido" },
  { texto: "El éxito es el resultado de la preparación y la oportunidad.", autor: "Bobby Unser" },
  { texto: "Tu vida es el reflejo de tus creencias.", autor: "Desconocido" },
  { texto: "La vida es un juego de pelota, golpea fuerte.", autor: "Desconocido" },
  { texto: "No busques la perfección en otros, búscala en ti.", autor: "Desconocido" },
  { texto: "La vida es lo que tú crees que es.", autor: "Desconocido" },
  { texto: "El éxito es la victoria sobre ti mismo.", autor: "Desconocido" },
  { texto: "Tu vida es tu responsabilidad, asúmela.", autor: "Desconocido" },
  { texto: "La vida es una serie de momentos mágicos.", autor: "Walt Disney" },
  { texto: "No dejes que el miedo te controle.", autor: "Desconocido" },
  { texto: "La vida es la mejor escuela.", autor: "Desconocido" },
  { texto: "Tu éxito es tu mejor amigo.", autor: "Desconocido" },
  { texto: "La vida es lo que tú haces que sea especial.", autor: "Desconocido" },
  { texto: "El éxito es la satisfacción personal.", autor: "Desconocido" },
  { texto: "Tu vida es un libro, escribe tu historia.", autor: "Desconocido" },
  { texto: "La vida es un lienzo en blanco, pinta tu futuro.", autor: "Desconocido" },
  { texto: "No busques igualar a otros, sé único.", autor: "Desconocido" },
  { texto: "La vida es un regalo que se abre cada día.", autor: "Desconocido" },
  { texto: "El éxito es para los que creen en sí mismos.", autor: "Desconocido" },
  { texto: "Tu vida es tu oportunidad, aprovéchala.", autor: "Desconocido" },
  { texto: "La vida no es esperar a morir, es empezar a vivir.", autor: "Maya Angelou" },
  { texto: "No subestimes tu capacidad de cambiar.", autor: "Desconocido" },
  { texto: "La vida es una bendición, vívela.", autor: "Desconocido" },
  { texto: "Tu éxito es tu mejor legado.", autor: "Desconocido" },
  { texto: "La vida es lo que haces con las segundas oportunidades.", autor: "Desconocido" },
  { texto: "El éxito es la acción, no la reacción.", autor: "Desconocido" },
  { texto: "Tu vida es tu tesoro, protégela.", autor: "Desconocido" },
  { texto: "La vida es una serie de decisiones correctas.", autor: "Desconocido" },
  { texto: "No temas al cambio, abráza lo.", autor: "Desconocido" },
  { texto: "La vida es hermosa para los que saben verla.", autor: "Desconocido" },
  { texto: "Tu éxito es tu mejor educación.", autor: "Desconocido" },
  { texto: "La vida es un viaje de autodescubrimiento.", autor: "Desconocido" },
  { texto: "El éxito es la realización de tus sueños.", autor: "Desconocido" },
  { texto: "Tu vida es tu iglesia, vívela con fe.", autor: "Desconocido" },
  { texto: "La vida es lo que tú creas que es posible.", autor: "Desconocido" },
  { texto: "No busques la verdad afuera, búscala adentro.", autor: "Desconocido" },
  { texto: "La vida es un desafío, supéralo.", autor: "Desconocido" },
  { texto: "Tu éxito es tu mejor defensa.", autor: "Desconocido" },
  { texto: "La vida es una sinfonía, toca tu nota.", autor: "Desconocido" },
  { texto: "El éxito es la paz de la mente.", autor: "Desconocido" },
  { texto: "Tu vida es tu mayor activo.", autor: "Desconocido" },
  { texto: "La vida es lo que construyes día a día.", autor: "Desconocido" },
  { texto: "No importa cuál sea tu pasado, tu futuro es limpio.", autor: "Desconocido" },
  { texto: "La vida es una oportunidad de aprender.", autor: "Desconocido" },
  { texto: "Tu éxito es tu mejor motivador.", autor: "Desconocido" },
  { texto: "La vida no es un accidente, es un regalo.", autor: "Desconocido" },
  { texto: "El éxito es la culminación de tu esfuerzo.", autor: "Desconocido" },
  { texto: "Tu vida es tu mejor ejemplo.", autor: "Desconocido" },
  { texto: "La vida es lo que sucede entre los sueños.", autor: "Desconocido" },
  { texto: "No busques la razón de vivir, crea la razón.", autor: "Desconocido" },
]

export function getFraseDelDia(): { texto: string; autor: string } {
  const hoy = new Date()
  const dayOfYear = Math.floor((hoy.getTime() - new Date(hoy.getFullYear(), 0, 0).getTime()) / 86400000)
  const index = (dayOfYear - 1) % frasesCelebres.length
  return frasesCelebres[index]
}
