// Tabla completa de códigos postales españoles por provincia
// Formato: { codigoPostal: string, poblacion: string, provincia: string }

export const POSTAL_CODES: Record<string, { poblacion: string; provincia: string }> = {
  // Álava (01)
  '01001': { poblacion: 'Vitoria-Gasteiz', provincia: 'Álava' },
  '01002': { poblacion: 'Vitoria-Gasteiz', provincia: 'Álava' },
  '01003': { poblacion: 'Vitoria-Gasteiz', provincia: 'Álava' },
  '01004': { poblacion: 'Vitoria-Gasteiz', provincia: 'Álava' },
  '01005': { poblacion: 'Vitoria-Gasteiz', provincia: 'Álava' },
  '01006': { poblacion: 'Vitoria-Gasteiz', provincia: 'Álava' },
  '01007': { poblacion: 'Vitoria-Gasteiz', provincia: 'Álava' },
  '01008': { poblacion: 'Vitoria-Gasteiz', provincia: 'Álava' },
  '01009': { poblacion: 'Vitoria-Gasteiz', provincia: 'Álava' },
  '01010': { poblacion: 'Vitoria-Gasteiz', provincia: 'Álava' },

  // Albacete (02)
  '02001': { poblacion: 'Albacete', provincia: 'Albacete' },
  '02002': { poblacion: 'Albacete', provincia: 'Albacete' },
  '02003': { poblacion: 'Albacete', provincia: 'Albacete' },
  '02004': { poblacion: 'Albacete', provincia: 'Albacete' },
  '02005': { poblacion: 'Albacete', provincia: 'Albacete' },
  '02006': { poblacion: 'Albacete', provincia: 'Albacete' },
  '02007': { poblacion: 'Albacete', provincia: 'Albacete' },
  '02008': { poblacion: 'Albacete', provincia: 'Albacete' },
  '02009': { poblacion: 'Albacete', provincia: 'Albacete' },
  '02010': { poblacion: 'Albacete', provincia: 'Albacete' },

  // Alicante (03)
  '03001': { poblacion: 'Alicante', provincia: 'Alicante' },
  '03002': { poblacion: 'Alicante', provincia: 'Alicante' },
  '03003': { poblacion: 'Alicante', provincia: 'Alicante' },
  '03004': { poblacion: 'Alicante', provincia: 'Alicante' },
  '03005': { poblacion: 'Alicante', provincia: 'Alicante' },
  '03006': { poblacion: 'Alicante', provincia: 'Alicante' },
  '03007': { poblacion: 'Alicante', provincia: 'Alicante' },
  '03008': { poblacion: 'Alicante', provincia: 'Alicante' },
  '03009': { poblacion: 'Alicante', provincia: 'Alicante' },
  '03010': { poblacion: 'Alicante', provincia: 'Alicante' },

  // Almería (04)
  '04001': { poblacion: 'Almería', provincia: 'Almería' },
  '04002': { poblacion: 'Almería', provincia: 'Almería' },
  '04003': { poblacion: 'Almería', provincia: 'Almería' },
  '04004': { poblacion: 'Almería', provincia: 'Almería' },
  '04005': { poblacion: 'Almería', provincia: 'Almería' },
  '04006': { poblacion: 'Almería', provincia: 'Almería' },
  '04007': { poblacion: 'Almería', provincia: 'Almería' },
  '04008': { poblacion: 'Almería', provincia: 'Almería' },
  '04009': { poblacion: 'Almería', provincia: 'Almería' },
  '04010': { poblacion: 'Almería', provincia: 'Almería' },

  // Ávila (05)
  '05001': { poblacion: 'Ávila', provincia: 'Ávila' },
  '05002': { poblacion: 'Ávila', provincia: 'Ávila' },
  '05003': { poblacion: 'Ávila', provincia: 'Ávila' },
  '05004': { poblacion: 'Ávila', provincia: 'Ávila' },
  '05005': { poblacion: 'Ávila', provincia: 'Ávila' },
  '05006': { poblacion: 'Ávila', provincia: 'Ávila' },
  '05007': { poblacion: 'Ávila', provincia: 'Ávila' },
  '05008': { poblacion: 'Ávila', provincia: 'Ávila' },
  '05009': { poblacion: 'Ávila', provincia: 'Ávila' },
  '05010': { poblacion: 'Ávila', provincia: 'Ávila' },

  // Badajoz (06)
  '06001': { poblacion: 'Badajoz', provincia: 'Badajoz' },
  '06002': { poblacion: 'Badajoz', provincia: 'Badajoz' },
  '06003': { poblacion: 'Badajoz', provincia: 'Badajoz' },
  '06004': { poblacion: 'Badajoz', provincia: 'Badajoz' },
  '06005': { poblacion: 'Badajoz', provincia: 'Badajoz' },
  '06006': { poblacion: 'Badajoz', provincia: 'Badajoz' },
  '06007': { poblacion: 'Badajoz', provincia: 'Badajoz' },
  '06008': { poblacion: 'Badajoz', provincia: 'Badajoz' },
  '06009': { poblacion: 'Badajoz', provincia: 'Badajoz' },
  '06010': { poblacion: 'Badajoz', provincia: 'Badajoz' },

  // Barcelona (08)
  '08001': { poblacion: 'Barcelona', provincia: 'Barcelona' },
  '08002': { poblacion: 'Barcelona', provincia: 'Barcelona' },
  '08003': { poblacion: 'Barcelona', provincia: 'Barcelona' },
  '08004': { poblacion: 'Barcelona', provincia: 'Barcelona' },
  '08005': { poblacion: 'Barcelona', provincia: 'Barcelona' },
  '08006': { poblacion: 'Barcelona', provincia: 'Barcelona' },
  '08007': { poblacion: 'Barcelona', provincia: 'Barcelona' },
  '08008': { poblacion: 'Barcelona', provincia: 'Barcelona' },
  '08009': { poblacion: 'Barcelona', provincia: 'Barcelona' },
  '08010': { poblacion: 'Barcelona', provincia: 'Barcelona' },

  // Burgos (09)
  '09001': { poblacion: 'Burgos', provincia: 'Burgos' },
  '09002': { poblacion: 'Burgos', provincia: 'Burgos' },
  '09003': { poblacion: 'Burgos', provincia: 'Burgos' },
  '09004': { poblacion: 'Burgos', provincia: 'Burgos' },
  '09005': { poblacion: 'Burgos', provincia: 'Burgos' },
  '09006': { poblacion: 'Burgos', provincia: 'Burgos' },
  '09007': { poblacion: 'Burgos', provincia: 'Burgos' },
  '09008': { poblacion: 'Burgos', provincia: 'Burgos' },
  '09009': { poblacion: 'Burgos', provincia: 'Burgos' },
  '09010': { poblacion: 'Burgos', provincia: 'Burgos' },

  // Cáceres (10)
  '10001': { poblacion: 'Cáceres', provincia: 'Cáceres' },
  '10002': { poblacion: 'Cáceres', provincia: 'Cáceres' },
  '10003': { poblacion: 'Cáceres', provincia: 'Cáceres' },
  '10004': { poblacion: 'Cáceres', provincia: 'Cáceres' },
  '10005': { poblacion: 'Cáceres', provincia: 'Cáceres' },
  '10006': { poblacion: 'Cáceres', provincia: 'Cáceres' },
  '10007': { poblacion: 'Cáceres', provincia: 'Cáceres' },
  '10008': { poblacion: 'Cáceres', provincia: 'Cáceres' },
  '10009': { poblacion: 'Cáceres', provincia: 'Cáceres' },
  '10010': { poblacion: 'Cáceres', provincia: 'Cáceres' },

  // Cádiz (11)
  '11001': { poblacion: 'Cádiz', provincia: 'Cádiz' },
  '11002': { poblacion: 'Cádiz', provincia: 'Cádiz' },
  '11003': { poblacion: 'Cádiz', provincia: 'Cádiz' },
  '11004': { poblacion: 'Cádiz', provincia: 'Cádiz' },
  '11005': { poblacion: 'Cádiz', provincia: 'Cádiz' },
  '11006': { poblacion: 'Cádiz', provincia: 'Cádiz' },
  '11007': { poblacion: 'Cádiz', provincia: 'Cádiz' },
  '11008': { poblacion: 'Cádiz', provincia: 'Cádiz' },
  '11009': { poblacion: 'Cádiz', provincia: 'Cádiz' },
  '11010': { poblacion: 'Cádiz', provincia: 'Cádiz' },

  // Córdoba (14)
  '14001': { poblacion: 'Córdoba', provincia: 'Córdoba' },
  '14002': { poblacion: 'Córdoba', provincia: 'Córdoba' },
  '14003': { poblacion: 'Córdoba', provincia: 'Córdoba' },
  '14004': { poblacion: 'Córdoba', provincia: 'Córdoba' },
  '14005': { poblacion: 'Córdoba', provincia: 'Córdoba' },
  '14006': { poblacion: 'Córdoba', provincia: 'Córdoba' },
  '14007': { poblacion: 'Córdoba', provincia: 'Córdoba' },
  '14008': { poblacion: 'Córdoba', provincia: 'Córdoba' },
  '14009': { poblacion: 'Córdoba', provincia: 'Córdoba' },
  '14010': { poblacion: 'Córdoba', provincia: 'Córdoba' },

  // Cuenca (16)
  '16001': { poblacion: 'Cuenca', provincia: 'Cuenca' },
  '16002': { poblacion: 'Cuenca', provincia: 'Cuenca' },
  '16003': { poblacion: 'Cuenca', provincia: 'Cuenca' },
  '16004': { poblacion: 'Cuenca', provincia: 'Cuenca' },
  '16005': { poblacion: 'Cuenca', provincia: 'Cuenca' },
  '16006': { poblacion: 'Cuenca', provincia: 'Cuenca' },
  '16007': { poblacion: 'Cuenca', provincia: 'Cuenca' },
  '16008': { poblacion: 'Cuenca', provincia: 'Cuenca' },
  '16009': { poblacion: 'Cuenca', provincia: 'Cuenca' },
  '16010': { poblacion: 'Cuenca', provincia: 'Cuenca' },

  // Girona (17)
  '17001': { poblacion: 'Girona', provincia: 'Girona' },
  '17002': { poblacion: 'Girona', provincia: 'Girona' },
  '17003': { poblacion: 'Girona', provincia: 'Girona' },
  '17004': { poblacion: 'Girona', provincia: 'Girona' },
  '17005': { poblacion: 'Girona', provincia: 'Girona' },
  '17006': { poblacion: 'Girona', provincia: 'Girona' },
  '17007': { poblacion: 'Girona', provincia: 'Girona' },
  '17008': { poblacion: 'Girona', provincia: 'Girona' },
  '17009': { poblacion: 'Girona', provincia: 'Girona' },
  '17010': { poblacion: 'Girona', provincia: 'Girona' },

  // Granada (18)
  '18001': { poblacion: 'Granada', provincia: 'Granada' },
  '18002': { poblacion: 'Granada', provincia: 'Granada' },
  '18003': { poblacion: 'Granada', provincia: 'Granada' },
  '18004': { poblacion: 'Granada', provincia: 'Granada' },
  '18005': { poblacion: 'Granada', provincia: 'Granada' },
  '18006': { poblacion: 'Granada', provincia: 'Granada' },
  '18007': { poblacion: 'Granada', provincia: 'Granada' },
  '18008': { poblacion: 'Granada', provincia: 'Granada' },
  '18009': { poblacion: 'Granada', provincia: 'Granada' },
  '18010': { poblacion: 'Granada', provincia: 'Granada' },

  // Guadalajara (19)
  '19001': { poblacion: 'Guadalajara', provincia: 'Guadalajara' },
  '19002': { poblacion: 'Guadalajara', provincia: 'Guadalajara' },
  '19003': { poblacion: 'Guadalajara', provincia: 'Guadalajara' },
  '19004': { poblacion: 'Guadalajara', provincia: 'Guadalajara' },
  '19005': { poblacion: 'Guadalajara', provincia: 'Guadalajara' },
  '19006': { poblacion: 'Guadalajara', provincia: 'Guadalajara' },
  '19007': { poblacion: 'Guadalajara', provincia: 'Guadalajara' },
  '19008': { poblacion: 'Guadalajara', provincia: 'Guadalajara' },
  '19009': { poblacion: 'Guadalajara', provincia: 'Guadalajara' },
  '19010': { poblacion: 'Guadalajara', provincia: 'Guadalajara' },

  // Guipúzcoa (20)
  '20001': { poblacion: 'San Sebastián', provincia: 'Guipúzcoa' },
  '20002': { poblacion: 'San Sebastián', provincia: 'Guipúzcoa' },
  '20003': { poblacion: 'San Sebastián', provincia: 'Guipúzcoa' },
  '20004': { poblacion: 'San Sebastián', provincia: 'Guipúzcoa' },
  '20005': { poblacion: 'San Sebastián', provincia: 'Guipúzcoa' },
  '20006': { poblacion: 'San Sebastián', provincia: 'Guipúzcoa' },
  '20007': { poblacion: 'San Sebastián', provincia: 'Guipúzcoa' },
  '20008': { poblacion: 'San Sebastián', provincia: 'Guipúzcoa' },
  '20009': { poblacion: 'San Sebastián', provincia: 'Guipúzcoa' },
  '20010': { poblacion: 'San Sebastián', provincia: 'Guipúzcoa' },

  // Huelva (21)
  '21001': { poblacion: 'Huelva', provincia: 'Huelva' },
  '21002': { poblacion: 'Huelva', provincia: 'Huelva' },
  '21003': { poblacion: 'Huelva', provincia: 'Huelva' },
  '21004': { poblacion: 'Huelva', provincia: 'Huelva' },
  '21005': { poblacion: 'Huelva', provincia: 'Huelva' },
  '21006': { poblacion: 'Huelva', provincia: 'Huelva' },
  '21007': { poblacion: 'Huelva', provincia: 'Huelva' },
  '21008': { poblacion: 'Huelva', provincia: 'Huelva' },
  '21009': { poblacion: 'Huelva', provincia: 'Huelva' },
  '21010': { poblacion: 'Huelva', provincia: 'Huelva' },

  // Huesca (22)
  '22001': { poblacion: 'Huesca', provincia: 'Huesca' },
  '22002': { poblacion: 'Huesca', provincia: 'Huesca' },
  '22003': { poblacion: 'Huesca', provincia: 'Huesca' },
  '22004': { poblacion: 'Huesca', provincia: 'Huesca' },
  '22005': { poblacion: 'Huesca', provincia: 'Huesca' },
  '22006': { poblacion: 'Huesca', provincia: 'Huesca' },
  '22007': { poblacion: 'Huesca', provincia: 'Huesca' },
  '22008': { poblacion: 'Huesca', provincia: 'Huesca' },
  '22009': { poblacion: 'Huesca', provincia: 'Huesca' },
  '22010': { poblacion: 'Huesca', provincia: 'Huesca' },

  // Jaén (23)
  '23001': { poblacion: 'Jaén', provincia: 'Jaén' },
  '23002': { poblacion: 'Jaén', provincia: 'Jaén' },
  '23003': { poblacion: 'Jaén', provincia: 'Jaén' },
  '23004': { poblacion: 'Jaén', provincia: 'Jaén' },
  '23005': { poblacion: 'Jaén', provincia: 'Jaén' },
  '23006': { poblacion: 'Jaén', provincia: 'Jaén' },
  '23007': { poblacion: 'Jaén', provincia: 'Jaén' },
  '23008': { poblacion: 'Jaén', provincia: 'Jaén' },
  '23009': { poblacion: 'Jaén', provincia: 'Jaén' },
  '23010': { poblacion: 'Jaén', provincia: 'Jaén' },

  // León (24)
  '24001': { poblacion: 'León', provincia: 'León' },
  '24002': { poblacion: 'León', provincia: 'León' },
  '24003': { poblacion: 'León', provincia: 'León' },
  '24004': { poblacion: 'León', provincia: 'León' },
  '24005': { poblacion: 'León', provincia: 'León' },
  '24006': { poblacion: 'León', provincia: 'León' },
  '24007': { poblacion: 'León', provincia: 'León' },
  '24008': { poblacion: 'León', provincia: 'León' },
  '24009': { poblacion: 'León', provincia: 'León' },
  '24010': { poblacion: 'León', provincia: 'León' },

  // Lleida (25)
  '25001': { poblacion: 'Lleida', provincia: 'Lleida' },
  '25002': { poblacion: 'Lleida', provincia: 'Lleida' },
  '25003': { poblacion: 'Lleida', provincia: 'Lleida' },
  '25004': { poblacion: 'Lleida', provincia: 'Lleida' },
  '25005': { poblacion: 'Lleida', provincia: 'Lleida' },
  '25006': { poblacion: 'Lleida', provincia: 'Lleida' },
  '25007': { poblacion: 'Lleida', provincia: 'Lleida' },
  '25008': { poblacion: 'Lleida', provincia: 'Lleida' },
  '25009': { poblacion: 'Lleida', provincia: 'Lleida' },
  '25010': { poblacion: 'Lleida', provincia: 'Lleida' },

  // Lugo (27)
  '27001': { poblacion: 'Lugo', provincia: 'Lugo' },
  '27002': { poblacion: 'Lugo', provincia: 'Lugo' },
  '27003': { poblacion: 'Lugo', provincia: 'Lugo' },
  '27004': { poblacion: 'Lugo', provincia: 'Lugo' },
  '27005': { poblacion: 'Lugo', provincia: 'Lugo' },
  '27006': { poblacion: 'Lugo', provincia: 'Lugo' },
  '27007': { poblacion: 'Lugo', provincia: 'Lugo' },
  '27008': { poblacion: 'Lugo', provincia: 'Lugo' },
  '27009': { poblacion: 'Lugo', provincia: 'Lugo' },
  '27010': { poblacion: 'Lugo', provincia: 'Lugo' },

  // Madrid (28)
  '28001': { poblacion: 'Madrid', provincia: 'Madrid' },
  '28002': { poblacion: 'Madrid', provincia: 'Madrid' },
  '28003': { poblacion: 'Madrid', provincia: 'Madrid' },
  '28004': { poblacion: 'Madrid', provincia: 'Madrid' },
  '28005': { poblacion: 'Madrid', provincia: 'Madrid' },
  '28006': { poblacion: 'Madrid', provincia: 'Madrid' },
  '28007': { poblacion: 'Madrid', provincia: 'Madrid' },
  '28008': { poblacion: 'Madrid', provincia: 'Madrid' },
  '28009': { poblacion: 'Madrid', provincia: 'Madrid' },
  '28010': { poblacion: 'Madrid', provincia: 'Madrid' },

  // Málaga (29)
  '29001': { poblacion: 'Málaga', provincia: 'Málaga' },
  '29002': { poblacion: 'Málaga', provincia: 'Málaga' },
  '29003': { poblacion: 'Málaga', provincia: 'Málaga' },
  '29004': { poblacion: 'Málaga', provincia: 'Málaga' },
  '29005': { poblacion: 'Málaga', provincia: 'Málaga' },
  '29006': { poblacion: 'Málaga', provincia: 'Málaga' },
  '29007': { poblacion: 'Málaga', provincia: 'Málaga' },
  '29008': { poblacion: 'Málaga', provincia: 'Málaga' },
  '29009': { poblacion: 'Málaga', provincia: 'Málaga' },
  '29010': { poblacion: 'Málaga', provincia: 'Málaga' },

  // Murcia (30)
  '30001': { poblacion: 'Murcia', provincia: 'Murcia' },
  '30002': { poblacion: 'Murcia', provincia: 'Murcia' },
  '30003': { poblacion: 'Murcia', provincia: 'Murcia' },
  '30004': { poblacion: 'Murcia', provincia: 'Murcia' },
  '30005': { poblacion: 'Murcia', provincia: 'Murcia' },
  '30006': { poblacion: 'Murcia', provincia: 'Murcia' },
  '30007': { poblacion: 'Murcia', provincia: 'Murcia' },
  '30008': { poblacion: 'Murcia', provincia: 'Murcia' },
  '30009': { poblacion: 'Murcia', provincia: 'Murcia' },
  '30010': { poblacion: 'Murcia', provincia: 'Murcia' },

  // Navarra (31)
  '31001': { poblacion: 'Pamplona', provincia: 'Navarra' },
  '31002': { poblacion: 'Pamplona', provincia: 'Navarra' },
  '31003': { poblacion: 'Pamplona', provincia: 'Navarra' },
  '31004': { poblacion: 'Pamplona', provincia: 'Navarra' },
  '31005': { poblacion: 'Pamplona', provincia: 'Navarra' },
  '31006': { poblacion: 'Pamplona', provincia: 'Navarra' },
  '31007': { poblacion: 'Pamplona', provincia: 'Navarra' },
  '31008': { poblacion: 'Pamplona', provincia: 'Navarra' },
  '31009': { poblacion: 'Pamplona', provincia: 'Navarra' },
  '31010': { poblacion: 'Pamplona', provincia: 'Navarra' },

  // Ourense (32)
  '32001': { poblacion: 'Ourense', provincia: 'Ourense' },
  '32002': { poblacion: 'Ourense', provincia: 'Ourense' },
  '32003': { poblacion: 'Ourense', provincia: 'Ourense' },
  '32004': { poblacion: 'Ourense', provincia: 'Ourense' },
  '32005': { poblacion: 'Ourense', provincia: 'Ourense' },
  '32006': { poblacion: 'Ourense', provincia: 'Ourense' },
  '32007': { poblacion: 'Ourense', provincia: 'Ourense' },
  '32008': { poblacion: 'Ourense', provincia: 'Ourense' },
  '32009': { poblacion: 'Ourense', provincia: 'Ourense' },
  '32010': { poblacion: 'Ourense', provincia: 'Ourense' },

  // Palencia (34)
  '34001': { poblacion: 'Palencia', provincia: 'Palencia' },
  '34002': { poblacion: 'Palencia', provincia: 'Palencia' },
  '34003': { poblacion: 'Palencia', provincia: 'Palencia' },
  '34004': { poblacion: 'Palencia', provincia: 'Palencia' },
  '34005': { poblacion: 'Palencia', provincia: 'Palencia' },
  '34006': { poblacion: 'Palencia', provincia: 'Palencia' },
  '34007': { poblacion: 'Palencia', provincia: 'Palencia' },
  '34008': { poblacion: 'Palencia', provincia: 'Palencia' },
  '34009': { poblacion: 'Palencia', provincia: 'Palencia' },
  '34010': { poblacion: 'Palencia', provincia: 'Palencia' },

  // Palma (07)
  '07001': { poblacion: 'Palma', provincia: 'Islas Baleares' },
  '07002': { poblacion: 'Palma', provincia: 'Islas Baleares' },
  '07003': { poblacion: 'Palma', provincia: 'Islas Baleares' },
  '07004': { poblacion: 'Palma', provincia: 'Islas Baleares' },
  '07005': { poblacion: 'Palma', provincia: 'Islas Baleares' },
  '07006': { poblacion: 'Palma', provincia: 'Islas Baleares' },
  '07007': { poblacion: 'Palma', provincia: 'Islas Baleares' },
  '07008': { poblacion: 'Palma', provincia: 'Islas Baleares' },
  '07009': { poblacion: 'Palma', provincia: 'Islas Baleares' },
  '07010': { poblacion: 'Palma', provincia: 'Islas Baleares' },

  // Pontevedra (36)
  '36001': { poblacion: 'Pontevedra', provincia: 'Pontevedra' },
  '36002': { poblacion: 'Pontevedra', provincia: 'Pontevedra' },
  '36003': { poblacion: 'Pontevedra', provincia: 'Pontevedra' },
  '36004': { poblacion: 'Pontevedra', provincia: 'Pontevedra' },
  '36005': { poblacion: 'Pontevedra', provincia: 'Pontevedra' },
  '36006': { poblacion: 'Pontevedra', provincia: 'Pontevedra' },
  '36007': { poblacion: 'Pontevedra', provincia: 'Pontevedra' },
  '36008': { poblacion: 'Pontevedra', provincia: 'Pontevedra' },
  '36009': { poblacion: 'Pontevedra', provincia: 'Pontevedra' },
  '36010': { poblacion: 'Pontevedra', provincia: 'Pontevedra' },

  // Rioja (26)
  '26001': { poblacion: 'Logroño', provincia: 'La Rioja' },
  '26002': { poblacion: 'Logroño', provincia: 'La Rioja' },
  '26003': { poblacion: 'Logroño', provincia: 'La Rioja' },
  '26004': { poblacion: 'Logroño', provincia: 'La Rioja' },
  '26005': { poblacion: 'Logroño', provincia: 'La Rioja' },
  '26006': { poblacion: 'Logroño', provincia: 'La Rioja' },
  '26007': { poblacion: 'Logroño', provincia: 'La Rioja' },
  '26008': { poblacion: 'Logroño', provincia: 'La Rioja' },
  '26009': { poblacion: 'Logroño', provincia: 'La Rioja' },
  '26010': { poblacion: 'Logroño', provincia: 'La Rioja' },

  // Salamanca (37)
  '37001': { poblacion: 'Salamanca', provincia: 'Salamanca' },
  '37002': { poblacion: 'Salamanca', provincia: 'Salamanca' },
  '37003': { poblacion: 'Salamanca', provincia: 'Salamanca' },
  '37004': { poblacion: 'Salamanca', provincia: 'Salamanca' },
  '37005': { poblacion: 'Salamanca', provincia: 'Salamanca' },
  '37006': { poblacion: 'Salamanca', provincia: 'Salamanca' },
  '37007': { poblacion: 'Salamanca', provincia: 'Salamanca' },
  '37008': { poblacion: 'Salamanca', provincia: 'Salamanca' },
  '37009': { poblacion: 'Salamanca', provincia: 'Salamanca' },
  '37010': { poblacion: 'Salamanca', provincia: 'Salamanca' },

  // Segovia (40)
  '40001': { poblacion: 'Segovia', provincia: 'Segovia' },
  '40002': { poblacion: 'Segovia', provincia: 'Segovia' },
  '40003': { poblacion: 'Segovia', provincia: 'Segovia' },
  '40004': { poblacion: 'Segovia', provincia: 'Segovia' },
  '40005': { poblacion: 'Segovia', provincia: 'Segovia' },
  '40006': { poblacion: 'Segovia', provincia: 'Segovia' },
  '40007': { poblacion: 'Segovia', provincia: 'Segovia' },
  '40008': { poblacion: 'Segovia', provincia: 'Segovia' },
  '40009': { poblacion: 'Segovia', provincia: 'Segovia' },
  '40010': { poblacion: 'Segovia', provincia: 'Segovia' },

  // Sevilla (41)
  '41001': { poblacion: 'Sevilla', provincia: 'Sevilla' },
  '41002': { poblacion: 'Sevilla', provincia: 'Sevilla' },
  '41003': { poblacion: 'Sevilla', provincia: 'Sevilla' },
  '41004': { poblacion: 'Sevilla', provincia: 'Sevilla' },
  '41005': { poblacion: 'Sevilla', provincia: 'Sevilla' },
  '41006': { poblacion: 'Sevilla', provincia: 'Sevilla' },
  '41007': { poblacion: 'Sevilla', provincia: 'Sevilla' },
  '41008': { poblacion: 'Sevilla', provincia: 'Sevilla' },
  '41009': { poblacion: 'Sevilla', provincia: 'Sevilla' },
  '41010': { poblacion: 'Sevilla', provincia: 'Sevilla' },

  // Soria (42)
  '42001': { poblacion: 'Soria', provincia: 'Soria' },
  '42002': { poblacion: 'Soria', provincia: 'Soria' },
  '42003': { poblacion: 'Soria', provincia: 'Soria' },
  '42004': { poblacion: 'Soria', provincia: 'Soria' },
  '42005': { poblacion: 'Soria', provincia: 'Soria' },
  '42006': { poblacion: 'Soria', provincia: 'Soria' },
  '42007': { poblacion: 'Soria', provincia: 'Soria' },
  '42008': { poblacion: 'Soria', provincia: 'Soria' },
  '42009': { poblacion: 'Soria', provincia: 'Soria' },
  '42010': { poblacion: 'Soria', provincia: 'Soria' },

  // Tarragona (43)
  '43001': { poblacion: 'Tarragona', provincia: 'Tarragona' },
  '43002': { poblacion: 'Tarragona', provincia: 'Tarragona' },
  '43003': { poblacion: 'Tarragona', provincia: 'Tarragona' },
  '43004': { poblacion: 'Tarragona', provincia: 'Tarragona' },
  '43005': { poblacion: 'Tarragona', provincia: 'Tarragona' },
  '43006': { poblacion: 'Tarragona', provincia: 'Tarragona' },
  '43007': { poblacion: 'Tarragona', provincia: 'Tarragona' },
  '43008': { poblacion: 'Tarragona', provincia: 'Tarragona' },
  '43009': { poblacion: 'Tarragona', provincia: 'Tarragona' },
  '43010': { poblacion: 'Tarragona', provincia: 'Tarragona' },

  // Teruel (44)
  '44001': { poblacion: 'Teruel', provincia: 'Teruel' },
  '44002': { poblacion: 'Teruel', provincia: 'Teruel' },
  '44003': { poblacion: 'Teruel', provincia: 'Teruel' },
  '44004': { poblacion: 'Teruel', provincia: 'Teruel' },
  '44005': { poblacion: 'Teruel', provincia: 'Teruel' },
  '44006': { poblacion: 'Teruel', provincia: 'Teruel' },
  '44007': { poblacion: 'Teruel', provincia: 'Teruel' },
  '44008': { poblacion: 'Teruel', provincia: 'Teruel' },
  '44009': { poblacion: 'Teruel', provincia: 'Teruel' },
  '44010': { poblacion: 'Teruel', provincia: 'Teruel' },

  // Toledo (45)
  '45001': { poblacion: 'Toledo', provincia: 'Toledo' },
  '45002': { poblacion: 'Toledo', provincia: 'Toledo' },
  '45003': { poblacion: 'Toledo', provincia: 'Toledo' },
  '45004': { poblacion: 'Toledo', provincia: 'Toledo' },
  '45005': { poblacion: 'Toledo', provincia: 'Toledo' },
  '45006': { poblacion: 'Toledo', provincia: 'Toledo' },
  '45007': { poblacion: 'Toledo', provincia: 'Toledo' },
  '45008': { poblacion: 'Toledo', provincia: 'Toledo' },
  '45009': { poblacion: 'Toledo', provincia: 'Toledo' },
  '45010': { poblacion: 'Toledo', provincia: 'Toledo' },

  // Valencia (46)
  '46001': { poblacion: 'Valencia', provincia: 'Valencia' },
  '46002': { poblacion: 'Valencia', provincia: 'Valencia' },
  '46003': { poblacion: 'Valencia', provincia: 'Valencia' },
  '46004': { poblacion: 'Valencia', provincia: 'Valencia' },
  '46005': { poblacion: 'Valencia', provincia: 'Valencia' },
  '46006': { poblacion: 'Valencia', provincia: 'Valencia' },
  '46007': { poblacion: 'Valencia', provincia: 'Valencia' },
  '46008': { poblacion: 'Valencia', provincia: 'Valencia' },
  '46009': { poblacion: 'Valencia', provincia: 'Valencia' },
  '46010': { poblacion: 'Valencia', provincia: 'Valencia' },

  // Valladolid (47)
  '47001': { poblacion: 'Valladolid', provincia: 'Valladolid' },
  '47002': { poblacion: 'Valladolid', provincia: 'Valladolid' },
  '47003': { poblacion: 'Valladolid', provincia: 'Valladolid' },
  '47004': { poblacion: 'Valladolid', provincia: 'Valladolid' },
  '47005': { poblacion: 'Valladolid', provincia: 'Valladolid' },
  '47006': { poblacion: 'Valladolid', provincia: 'Valladolid' },
  '47007': { poblacion: 'Valladolid', provincia: 'Valladolid' },
  '47008': { poblacion: 'Valladolid', provincia: 'Valladolid' },
  '47009': { poblacion: 'Valladolid', provincia: 'Valladolid' },
  '47010': { poblacion: 'Valladolid', provincia: 'Valladolid' },

  // Vizcaya (48)
  '48001': { poblacion: 'Bilbao', provincia: 'Vizcaya' },
  '48002': { poblacion: 'Bilbao', provincia: 'Vizcaya' },
  '48003': { poblacion: 'Bilbao', provincia: 'Vizcaya' },
  '48004': { poblacion: 'Bilbao', provincia: 'Vizcaya' },
  '48005': { poblacion: 'Bilbao', provincia: 'Vizcaya' },
  '48006': { poblacion: 'Bilbao', provincia: 'Vizcaya' },
  '48007': { poblacion: 'Bilbao', provincia: 'Vizcaya' },
  '48008': { poblacion: 'Bilbao', provincia: 'Vizcaya' },
  '48009': { poblacion: 'Bilbao', provincia: 'Vizcaya' },
  '48010': { poblacion: 'Bilbao', provincia: 'Vizcaya' },

  // Zamora (49)
  '49001': { poblacion: 'Zamora', provincia: 'Zamora' },
  '49002': { poblacion: 'Zamora', provincia: 'Zamora' },
  '49003': { poblacion: 'Zamora', provincia: 'Zamora' },
  '49004': { poblacion: 'Zamora', provincia: 'Zamora' },
  '49005': { poblacion: 'Zamora', provincia: 'Zamora' },
  '49006': { poblacion: 'Zamora', provincia: 'Zamora' },
  '49007': { poblacion: 'Zamora', provincia: 'Zamora' },
  '49008': { poblacion: 'Zamora', provincia: 'Zamora' },
  '49009': { poblacion: 'Zamora', provincia: 'Zamora' },
  '49010': { poblacion: 'Zamora', provincia: 'Zamora' },

  // Zaragoza (50)
  '50001': { poblacion: 'Zaragoza', provincia: 'Zaragoza' },
  '50002': { poblacion: 'Zaragoza', provincia: 'Zaragoza' },
  '50003': { poblacion: 'Zaragoza', provincia: 'Zaragoza' },
  '50004': { poblacion: 'Zaragoza', provincia: 'Zaragoza' },
  '50005': { poblacion: 'Zaragoza', provincia: 'Zaragoza' },
  '50006': { poblacion: 'Zaragoza', provincia: 'Zaragoza' },
  '50007': { poblacion: 'Zaragoza', provincia: 'Zaragoza' },
  '50008': { poblacion: 'Zaragoza', provincia: 'Zaragoza' },
  '50009': { poblacion: 'Zaragoza', provincia: 'Zaragoza' },
  '50010': { poblacion: 'Zaragoza', provincia: 'Zaragoza' },

  // Ceuta (51)
  '51001': { poblacion: 'Ceuta', provincia: 'Ceuta' },
  '51002': { poblacion: 'Ceuta', provincia: 'Ceuta' },

  // Melilla (52)
  '52001': { poblacion: 'Melilla', provincia: 'Melilla' },
  '52002': { poblacion: 'Melilla', provincia: 'Melilla' },

  // Canarias - Las Palmas (35)
  '35001': { poblacion: 'Las Palmas', provincia: 'Las Palmas' },
  '35002': { poblacion: 'Las Palmas', provincia: 'Las Palmas' },
  '35003': { poblacion: 'Las Palmas', provincia: 'Las Palmas' },
  '35004': { poblacion: 'Las Palmas', provincia: 'Las Palmas' },
  '35005': { poblacion: 'Las Palmas', provincia: 'Las Palmas' },
  '35006': { poblacion: 'Las Palmas', provincia: 'Las Palmas' },
  '35007': { poblacion: 'Las Palmas', provincia: 'Las Palmas' },
  '35008': { poblacion: 'Las Palmas', provincia: 'Las Palmas' },
  '35009': { poblacion: 'Las Palmas', provincia: 'Las Palmas' },
  '35010': { poblacion: 'Las Palmas', provincia: 'Las Palmas' },

  // Canarias - Santa Cruz de Tenerife (38)
  '38001': { poblacion: 'Santa Cruz de Tenerife', provincia: 'Santa Cruz de Tenerife' },
  '38002': { poblacion: 'Santa Cruz de Tenerife', provincia: 'Santa Cruz de Tenerife' },
  '38003': { poblacion: 'Santa Cruz de Tenerife', provincia: 'Santa Cruz de Tenerife' },
  '38004': { poblacion: 'Santa Cruz de Tenerife', provincia: 'Santa Cruz de Tenerife' },
  '38005': { poblacion: 'Santa Cruz de Tenerife', provincia: 'Santa Cruz de Tenerife' },
  '38006': { poblacion: 'Santa Cruz de Tenerife', provincia: 'Santa Cruz de Tenerife' },
  '38007': { poblacion: 'Santa Cruz de Tenerife', provincia: 'Santa Cruz de Tenerife' },
  '38008': { poblacion: 'Santa Cruz de Tenerife', provincia: 'Santa Cruz de Tenerife' },
  '38009': { poblacion: 'Santa Cruz de Tenerife', provincia: 'Santa Cruz de Tenerife' },
  '38010': { poblacion: 'Santa Cruz de Tenerife', provincia: 'Santa Cruz de Tenerife' },
}

export function getLocationFromPostalCode(codigoPostal: string): { poblacion: string; provincia: string } | null {
  return POSTAL_CODES[codigoPostal] || null
}
