import { db } from '@/lib/db'

const PAISES_DATA = [
  { nombre: 'Afganistán', codigo: 'AF' },
  { nombre: 'Albania', codigo: 'AL' },
  { nombre: 'Alemania', codigo: 'DE' },
  { nombre: 'Andorra', codigo: 'AD' },
  { nombre: 'Angola', codigo: 'AO' },
  { nombre: 'Antigua y Barbuda', codigo: 'AG' },
  { nombre: 'Arabia Saudí', codigo: 'SA' },
  { nombre: 'Argelia', codigo: 'DZ' },
  { nombre: 'Argentina', codigo: 'AR' },
  { nombre: 'Armenia', codigo: 'AM' },
  { nombre: 'Aruba', codigo: 'AW' },
  { nombre: 'Australia', codigo: 'AU' },
  { nombre: 'Austria', codigo: 'AT' },
  { nombre: 'Azerbaiyán', codigo: 'AZ' },
  { nombre: 'Bahamas', codigo: 'BS' },
  { nombre: 'Bangladés', codigo: 'BD' },
  { nombre: 'Barbados', codigo: 'BB' },
  { nombre: 'Baréin', codigo: 'BH' },
  { nombre: 'Bélgica', codigo: 'BE' },
  { nombre: 'Belice', codigo: 'BZ' },
  { nombre: 'Benín', codigo: 'BJ' },
  { nombre: 'Bermudas', codigo: 'BM' },
  { nombre: 'Bielorrusia', codigo: 'BY' },
  { nombre: 'Birmania', codigo: 'MM' },
  { nombre: 'Bolivia', codigo: 'BO' },
  { nombre: 'Bosnia y Herzegovina', codigo: 'BA' },
  { nombre: 'Botsuana', codigo: 'BW' },
  { nombre: 'Brasil', codigo: 'BR' },
  { nombre: 'Brunei', codigo: 'BN' },
  { nombre: 'Bulgaria', codigo: 'BG' },
  { nombre: 'Burkina Faso', codigo: 'BF' },
  { nombre: 'Burundi', codigo: 'BI' },
  { nombre: 'Bután', codigo: 'BT' },
  { nombre: 'Cabo Verde', codigo: 'CV' },
  { nombre: 'Camboya', codigo: 'KH' },
  { nombre: 'Camerún', codigo: 'CM' },
  { nombre: 'Canadá', codigo: 'CA' },
  { nombre: 'Catar', codigo: 'QA' },
  { nombre: 'Chad', codigo: 'TD' },
  { nombre: 'Chile', codigo: 'CL' },
  { nombre: 'China', codigo: 'CN' },
  { nombre: 'Chipre', codigo: 'CY' },
  { nombre: 'Colombia', codigo: 'CO' },
  { nombre: 'Comoras', codigo: 'KM' },
  { nombre: 'Congo', codigo: 'CG' },
  { nombre: 'Corea del Norte', codigo: 'KP' },
  { nombre: 'Corea del Sur', codigo: 'KR' },
  { nombre: 'Costa Rica', codigo: 'CR' },
  { nombre: 'Croacia', codigo: 'HR' },
  { nombre: 'Cuba', codigo: 'CU' },
  { nombre: 'Curazao', codigo: 'CW' },
  { nombre: 'Dinamarca', codigo: 'DK' },
  { nombre: 'Djibuti', codigo: 'DJ' },
  { nombre: 'Dominica', codigo: 'DM' },
  { nombre: 'República Dominicana', codigo: 'DO' },
  { nombre: 'Ecuador', codigo: 'EC' },
  { nombre: 'Egipto', codigo: 'EG' },
  { nombre: 'Emiratos Árabes Unidos', codigo: 'AE' },
  { nombre: 'El Salvador', codigo: 'SV' },
  { nombre: 'Eritrea', codigo: 'ER' },
  { nombre: 'Eslovaquia', codigo: 'SK' },
  { nombre: 'Eslovenia', codigo: 'SI' },
  { nombre: 'España', codigo: 'ES' },
  { nombre: 'Estados Unidos', codigo: 'US' },
  { nombre: 'Estonia', codigo: 'EE' },
  { nombre: 'Eswatini', codigo: 'SZ' },
  { nombre: 'Etiopía', codigo: 'ET' },
  { nombre: 'Filipinas', codigo: 'PH' },
  { nombre: 'Finlandia', codigo: 'FI' },
  { nombre: 'Fiyi', codigo: 'FJ' },
  { nombre: 'Francia', codigo: 'FR' },
  { nombre: 'Gabón', codigo: 'GA' },
  { nombre: 'Gambia', codigo: 'GM' },
  { nombre: 'Georgia', codigo: 'GE' },
  { nombre: 'Georgia del Sur e Islas Sandwich del Sur', codigo: 'GS' },
  { nombre: 'Gibraltar', codigo: 'GI' },
  { nombre: 'Grecia', codigo: 'GR' },
  { nombre: 'Groenlandia', codigo: 'GL' },
  { nombre: 'Guadalupe', codigo: 'GP' },
  { nombre: 'Guam', codigo: 'GU' },
  { nombre: 'Guatemala', codigo: 'GT' },
  { nombre: 'Guayana Francesa', codigo: 'GF' },
  { nombre: 'Guayana Holandesa', codigo: 'SR' },
  { nombre: 'Guernésey', codigo: 'GG' },
  { nombre: 'Guinea', codigo: 'GN' },
  { nombre: 'Guinea Ecuatorial', codigo: 'GQ' },
  { nombre: 'Guinea-Bisáu', codigo: 'GW' },
  { nombre: 'Guyana', codigo: 'GY' },
  { nombre: 'Haití', codigo: 'HT' },
  { nombre: 'Holanda', codigo: 'NL' },
  { nombre: 'Honduras', codigo: 'HN' },
  { nombre: 'Hong Kong', codigo: 'HK' },
  { nombre: 'Hungría', codigo: 'HU' },
  { nombre: 'Irak', codigo: 'IQ' },
  { nombre: 'Irán', codigo: 'IR' },
  { nombre: 'Irlanda', codigo: 'IE' },
  { nombre: 'Islandia', codigo: 'IS' },
  { nombre: 'Islas Åland', codigo: 'AX' },
  { nombre: 'Islas Caimán', codigo: 'KY' },
  { nombre: 'Islas Cocos', codigo: 'CC' },
  { nombre: 'Islas Cook', codigo: 'CK' },
  { nombre: 'Islas Feroe', codigo: 'FO' },
  { nombre: 'Islas Malvinas', codigo: 'FK' },
  { nombre: 'Islas Marianas del Norte', codigo: 'MP' },
  { nombre: 'Islas Marshall', codigo: 'MH' },
  { nombre: 'Islas Salomón', codigo: 'SB' },
  { nombre: 'Islas Turcas y Caicos', codigo: 'TC' },
  { nombre: 'Islas Vírgenes Británicas', codigo: 'VG' },
  { nombre: 'Islas Vírgenes de EE.UU.', codigo: 'VI' },
  { nombre: 'Israel', codigo: 'IL' },
  { nombre: 'Italia', codigo: 'IT' },
  { nombre: 'Jamaica', codigo: 'JM' },
  { nombre: 'Japón', codigo: 'JP' },
  { nombre: 'Jersey', codigo: 'JE' },
  { nombre: 'Jordania', codigo: 'JO' },
  { nombre: 'Kazajistán', codigo: 'KZ' },
  { nombre: 'Kenia', codigo: 'KE' },
  { nombre: 'Kirguistán', codigo: 'KG' },
  { nombre: 'Kiribati', codigo: 'KI' },
  { nombre: 'Kuwait', codigo: 'KW' },
  { nombre: 'Laos', codigo: 'LA' },
  { nombre: 'Lesoto', codigo: 'LS' },
  { nombre: 'Letonia', codigo: 'LV' },
  { nombre: 'Líbano', codigo: 'LB' },
  { nombre: 'Liberia', codigo: 'LR' },
  { nombre: 'Libia', codigo: 'LY' },
  { nombre: 'Liechtenstein', codigo: 'LI' },
  { nombre: 'Lituania', codigo: 'LT' },
  { nombre: 'Luxemburgo', codigo: 'LU' },
  { nombre: 'Macao', codigo: 'MO' },
  { nombre: 'Macedonia del Norte', codigo: 'MK' },
  { nombre: 'Madagascar', codigo: 'MG' },
  { nombre: 'Malasia', codigo: 'MY' },
  { nombre: 'Malaui', codigo: 'MW' },
  { nombre: 'Maldivas', codigo: 'MV' },
  { nombre: 'Mali', codigo: 'ML' },
  { nombre: 'Malta', codigo: 'MT' },
  { nombre: 'Marruecos', codigo: 'MA' },
  { nombre: 'Martinica', codigo: 'MQ' },
  { nombre: 'Mauricio', codigo: 'MU' },
  { nombre: 'Mauritania', codigo: 'MR' },
  { nombre: 'Mayotte', codigo: 'YT' },
  { nombre: 'Melilla', codigo: 'ML' },
  { nombre: 'México', codigo: 'MX' },
  { nombre: 'Micronesia', codigo: 'FM' },
  { nombre: 'Moldavia', codigo: 'MD' },
  { nombre: 'Mónaco', codigo: 'MC' },
  { nombre: 'Mongolia', codigo: 'MN' },
  { nombre: 'Montenegro', codigo: 'ME' },
  { nombre: 'Montserrat', codigo: 'MS' },
  { nombre: 'Mozambique', codigo: 'MZ' },
  { nombre: 'Namibia', codigo: 'NA' },
  { nombre: 'Nauru', codigo: 'NR' },
  { nombre: 'Nepal', codigo: 'NP' },
  { nombre: 'Nicaragua', codigo: 'NI' },
  { nombre: 'Níger', codigo: 'NE' },
  { nombre: 'Nigeria', codigo: 'NG' },
  { nombre: 'Niue', codigo: 'NU' },
  { nombre: 'Noruega', codigo: 'NO' },
  { nombre: 'Nueva Caledonia', codigo: 'NC' },
  { nombre: 'Nueva Zelanda', codigo: 'NZ' },
  { nombre: 'Omán', codigo: 'OM' },
  { nombre: 'Pakistán', codigo: 'PK' },
  { nombre: 'Palaos', codigo: 'PW' },
  { nombre: 'Palestina', codigo: 'PS' },
  { nombre: 'Panamá', codigo: 'PA' },
  { nombre: 'Papúa Nueva Guinea', codigo: 'PG' },
  { nombre: 'Paraguay', codigo: 'PY' },
  { nombre: 'Perú', codigo: 'PE' },
  { nombre: 'Polinesia Francesa', codigo: 'PF' },
  { nombre: 'Polonia', codigo: 'PL' },
  { nombre: 'Portugal', codigo: 'PT' },
  { nombre: 'Puerto Rico', codigo: 'PR' },
  { nombre: 'Qatar', codigo: 'QA' },
  { nombre: 'Reino Unido', codigo: 'GB' },
  { nombre: 'República Centroafricana', codigo: 'CF' },
  { nombre: 'República Checa', codigo: 'CZ' },
  { nombre: 'República Democrática del Congo', codigo: 'CD' },
  { nombre: 'Reunión', codigo: 'RE' },
  { nombre: 'Ruanda', codigo: 'RW' },
  { nombre: 'Rumania', codigo: 'RO' },
  { nombre: 'Rusia', codigo: 'RU' },
  { nombre: 'Sahara Occidental', codigo: 'EH' },
  { nombre: 'Samoa', codigo: 'WS' },
  { nombre: 'Samoa Americana', codigo: 'AS' },
  { nombre: 'San Bartolomé', codigo: 'BL' },
  { nombre: 'San Cristóbal y Nieves', codigo: 'KN' },
  { nombre: 'San Marino', codigo: 'SM' },
  { nombre: 'San Martín', codigo: 'SX' },
  { nombre: 'San Pedro y Miquelón', codigo: 'PM' },
  { nombre: 'Santa Elena', codigo: 'SH' },
  { nombre: 'Santa Lucía', codigo: 'LC' },
  { nombre: 'Santo Tomé y Príncipe', codigo: 'ST' },
  { nombre: 'Senegal', codigo: 'SN' },
  { nombre: 'Serbia', codigo: 'RS' },
  { nombre: 'Seychelles', codigo: 'SC' },
  { nombre: 'Sierra Leona', codigo: 'SL' },
  { nombre: 'Singapur', codigo: 'SG' },
  { nombre: 'Siria', codigo: 'SY' },
  { nombre: 'Somalia', codigo: 'SO' },
  { nombre: 'Sri Lanka', codigo: 'LK' },
  { nombre: 'Sudáfrica', codigo: 'ZA' },
  { nombre: 'Sudán', codigo: 'SD' },
  { nombre: 'Sudán del Sur', codigo: 'SS' },
  { nombre: 'Suecia', codigo: 'SE' },
  { nombre: 'Suiza', codigo: 'CH' },
  { nombre: 'Surinam', codigo: 'SR' },
  { nombre: 'Tailandia', codigo: 'TH' },
  { nombre: 'Taiwán', codigo: 'TW' },
  { nombre: 'Tanzania', codigo: 'TZ' },
  { nombre: 'Tayikistán', codigo: 'TJ' },
  { nombre: 'Timor Oriental', codigo: 'TL' },
  { nombre: 'Togo', codigo: 'TG' },
  { nombre: 'Tokelau', codigo: 'TK' },
  { nombre: 'Tonga', codigo: 'TO' },
  { nombre: 'Trinidad y Tobago', codigo: 'TT' },
  { nombre: 'Túnez', codigo: 'TN' },
  { nombre: 'Turkmenistán', codigo: 'TM' },
  { nombre: 'Tuvalú', codigo: 'TV' },
  { nombre: 'Ucrania', codigo: 'UA' },
  { nombre: 'Uganda', codigo: 'UG' },
  { nombre: 'Uruguay', codigo: 'UY' },
  { nombre: 'Uzbekistán', codigo: 'UZ' },
  { nombre: 'Vanuatu', codigo: 'VU' },
  { nombre: 'Vaticano', codigo: 'VA' },
  { nombre: 'Venezuela', codigo: 'VE' },
  { nombre: 'Vietnam', codigo: 'VN' },
  { nombre: 'Wallis y Futuna', codigo: 'WF' },
  { nombre: 'Yemen', codigo: 'YE' },
  { nombre: 'Zambia', codigo: 'ZM' },
  { nombre: 'Zimbabue', codigo: 'ZW' },
]

async function main() {
  try {
    // Verificar si ya existen países
    const count = await db.pais.count()
    if (count > 0) {
      console.log(`✅ Ya existen ${count} países en la BD`)
      return
    }

    console.log('🌍 Insertando países...')
    const created = await db.pais.createMany({
      data: PAISES_DATA,
      skipDuplicates: true,
    })

    console.log(`✅ Se han insertado ${created.count} países`)
  } catch (error) {
    console.error('❌ Error:', error)
    process.exit(1)
  }
}

main()
